### ISSUE TITLE
I keep getting this error when I enter website URL

### ISSUE THREAD

**Issue by TrancedZen** [s0md3v/Blazy#14]
I can get the program to run fine. When I'm ask to enter a URL it says:
Traceback (most recent call last):
  File "blazy.py", line 48, in <module>
    br.open(url)
  File "/home/home/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 253, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/home/home/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 283, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/home/home/.local/lib/python2.7/site-packages/mechanize/_opener.py", line 193, in open
    response = urlopen(self, req, data)
  File "/home/home/.local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 353, in _open
    '_open', req)
  File "/home/home/.local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 341, in _call_chain
    result = func(*args)
  File "/home/home/.local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1209, in https_open
    return self.do_open(conn_factory, req)
  File "/home/home/.local/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1156, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by s0md3v** [comment]
This project is no longer being maintained and will be rewritten in near future.

**Comment by thehappydinoa** [comment]
Please try adding `http(s)://` before the domain
